language: node_js
node_js:
- node
addons:
  sauce_connect: true
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install
script:
- npm test
env:
  global:
  - secure: boN2U1QeNc3L7Y/k/e6aAYfrx2x1lXoMSoZNqUpfgAU1iIWzEiJs8Qs5dzRlIwDPNpXBapN22CggKT68OdLP/cI116l8nun2Hisn4EA/jNXY+Sd2tezFsaBVr3qiYELz6ULKWoBky7gTpVlcGl4r0N+tuRtlKps8yj8wch/3oWVPkLQvqgFoSt90vsFMEeEWiujWMR8ASS5R7ze0mQtO8UEKyK30HbTMuH0E2R72XIrr2uMNiIN/G9Yua8I7YrLuqRcrAKil8yFj7LcMM9+e4OkPOXQUuU4/W0dyCP67Q1wbipCsUZblrC7xyu5okiRi/sxlTUSU+TcBvUYNtFW8gzxJty54vharwBmwPjydNr4a1qC5FEzaAZb0GLji8DElT1yeYPm7Z7uvwi4cMBrxPZjY0dx8eVsBjzCa6Wv6cmroNfPXdk4eiTtOa8eERTc3LzGQio2RPih+q6B8TUVtgu2yy47tJigNEgf44nQ4Mt54yQJwGOIFnN/4gj40QA9XoGmuzAMX0Avu4d9UVy8+g4MAhoAyctZl9uIUTnHUstB67AVrijGU4/b02dMrEhiC8fDM0lJuz66KjU1v4KcDwybPaJ0pjx9bxgQCAxOVYVdU16VMdjLWQLBDfTVCg3NOGKuKViI8yN0apOFDawXUaCCJDZl+SbODLOXR/oiL3Hw=
  - secure: S5PxbQAoc68174l6s0hBDr4DQ047HfP16Mucz9d87zt1wkqre4rNJgmq4XhvzuJ9HBtfttFDzzEaF40IlwMFm+G2U4fdHytGLYnNmjn5FRGiCL/qXl13y5xkkMJU4saSStleWoHXTM0c9nrydozJHZrDreMQH8GfZXMxkRC+SehE2tJNOaHZ3Y3hsSgF8vbiHQpSCvJkUxGkfYLioGa1uuWvCLe3VhGxvnIboQuKISLOisS3HFfRM6CO/z3RgSJcrS1nHjSd7QwNTwwYiSyo1Hmij0dmg4dFrL80/KFYxLcum4HcZf0hIpT4ty7uEDBI+COw0yirGNNvyN2NEbCnXsaDuA4N865ssHM0FQnw1Z9LEfWJBrV65EWws906eeI0uFn85kviXoJwXzZ3HTof2WQ+J3z0UYRt7R+L7LYz0Ncb9tyiWJaB0i3lNK4XbLd9fYArfit4Rc3z7D8xGYa0V56BD3mNoTnMSM7Ioq9m4l944Ss4EtAuDjGIVrAXpEQDGtEik/tYonY/H9F3THlMHG351IEWOyRTDAFzxJCw1spb+e0w/4tvd+fLMU+0BJo4rj8xKxbFPrGttiPgCAvtNsnv3JqghZQH/QhBabnyLR/qkEf67XQsSLW/m0OP3AV9KA/sKgaIKpCSoIsDABIB8HjZRJo7lfFtNdT2YNPkhoI=
